sh_binary(
    name = "build_pip_pkg",
    srcs = ["build_pip_pkg.sh"],
    data = [
        # "//multidim_image_augmentation/LICENSE",
        "MANIFEST.in",
        "setup.py",
        "//multidim_image_augmentation:deformation_utils",
    ],
)
